### ISSUE TITLE
Feedstock package is much slower than manual install on Mac

### ISSUE THREAD

**Issue by matthiasdiener** [conda-forge/pyopencl-feedstock#116]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With this (admittedly silly) microbenchmark, pyopencl is more than 2x slower on my M1 compared to running `pip install . -v` on the same pyopencl version (same pocl version, 5.0):

```python
import pyopencl as cl
import time

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

prg = cl.Program(ctx, """__kernel void f() {} """).build()

knl = prg.f

# Warmup
knl(queue, (50, 50), None)
knl(queue, (50, 50), None)
knl(queue, (50, 50), None)

ncalls = 1000000

start = time.time()

for _ in range(ncalls):
    knl(queue, (50, 50), None)

queue.finish()

stop = time.time()

print(f"v{cl.VERSION_TEXT} {ncalls=} ran in {stop-start} s")
```

| Installation Method | Version | ncalls | Time |
| --- | --- | --- | --- |
| conda package | 2024.2.2 | 1000000 | 4.26 s |
| manual install | 2024.2.2 | 1000000 | 2.02 s |

Perhaps related to some ocl-icd difference?

### Installed packages

```shell
---
```

### Environment info

```shell
---
```

**Comment by inducer** [comment]
That's an interesting observation, very weird. Is the behavior the same on Linux? If so, we could dig into why that's the case using perf.

Another idea: is there a discrepancy in how the packages are built? E.g. debug vs not?

**Comment by matthiasdiener** [comment]
I was able to reproduce this issue with different siteconf.py configs. It seems to be related to the ocl loader, so possibly just an issue on Mac for now.

Fast version (empty `siteconf.py`), uses MacOS OpenCL framework:

```
-- Looking for CL_VERSION_3_0
-- Looking for CL_VERSION_3_0 - not found
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenCL.framework
```

Slow version (`siteconf.py` modified to point `CL_INC_DIR`, `CL_LIB_DIR`, and `CL_LIBNAME` to the [`khronos-opencl-icd-loader`](https://github.com/conda-forge/khronos-opencl-icd-loader-feedstock/tree/main) package in a conda env):

```
-- Looking for CL_VERSION_3_0
-- Looking for CL_VERSION_3_0 - found
-- Found OpenCL: /Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/libOpenCL.dylib (found version "3.0")
```

**Comment by matthiasdiener** [comment]
Nevermind, I just saw that in the fast case, it is running with Apple CL, not pocl, so likely not an issue in this package.
