### ISSUE TITLE
2018.2 osx_pocl_opencl build isn't built against pocl

### ISSUE THREAD

**Issue by mattwala** [conda-forge/pyopencl-feedstock#26]
Updating to 2018.2 on my Mac gets me the following:

```
The following packages will be UPDATED:

    pyopencl: 2018.1.1-py36_osx_pocl_opencl_2 conda-forge [osx_pocl_opencl] --> 2018.2-py36_osx_pocl_openclh1b5f808_0 conda-forge [osx_pocl_opencl]

Proceed ([y]/n)? y

pyopencl-2018. 100% |##############################################################################################################| Time: 0:00:00   2.95 MB/s
(inteq) $ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> cl._csc()
Choose platform:
[0] <pyopencl.Platform 'Apple' at 0x7fff0000>
Choice [0]:
Choose device(s):
[0] <pyopencl.Device 'Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz' on 'Apple' at 0xffffffff>
[1] <pyopencl.Device 'Intel(R) Iris(TM) Graphics 6100' on 'Apple' at 0x1024500>
```

**Comment by inducer** [comment]
cc @isuruf

**Comment by inducer** [comment]
@mattwala, thanks for reporting this!

@isuruf, thanks for working on a fix in #27!

**Comment by inducer** [comment]
It's not clear that the fix in #27 worked. The pyopencl 2018.2 conda package will install, but when I say
```
conda install osx-pocl-opencl pocl
```
conda responds with
```
The following packages will be DOWNGRADED:

    pyopencl:        2018.2-py36h81a3be6_1 conda-forge --> 2018.1.1-py36_osx_pocl_opencl_2 conda-forge [osx_pocl_opencl]
```
indicating that 2018.2 + pocl is still not available, although the relevant [builds](https://travis-ci.org/conda-forge/pyopencl-feedstock) have completed.

**Comment by inducer** [comment]
(Tried on appletini just now.)

**Comment by isuruf** [comment]
conda solver is unpredictable. Can you try `conda install osx-pocl-opencl pocl pyopencl`?

**Comment by inducer** [comment]
> conda solver is unpredictable. Can you try `conda install osx-pocl-opencl pocl pyopencl`?

Wow. Yes, that worked around it. Thanks!
/close

**Comment by mattwala** [comment]
I can confirm that this now works. Thank you @isuruf and @inducer! @inducer: I'm assuming you meant to close this, so I will.
