### ISSUE TITLE
clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR >

### ISSUE THREAD

**Issue by peter73421** [conda-forge/pyopencl-feedstock#32]
I have Intel OpenCL SDK installed and by using anaconda pyopencl I have this error ..

```
(cl) ~/anaconda3$ python 
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> cl.get_platforms()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

```
what is missing of configuration for pyopencl?

**Comment by isuruf** [comment]
See https://documen.tician.de/pyopencl/misc.html#using-vendor-supplied-opencl-drivers-linux

**Comment by peter73421** [comment]
From that doc not much clear information.
I use anaconda instead of miniconda.
Does this apply as well fór standard anaconda install?
What excatly needs to be copied where (headers, so libs, icd, etc..)?



út 13. 11. 2018 16:32 odesílatel Isuru Fernando <notifications@github.com>
napsal:

**Comment by isuruf** [comment]
You need to copy the icds to `/WHERE/YOU/INSTALLED/ANACONDA/etc/OpenCL/vendors`

**Comment by peter73421** [comment]
I have Linux machine with Intel CPU and Intel HD Graphics and using Intel
OpenCL SDK/Driver.

1. Device: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
 1.1 Hardware version: OpenCL 2.1 (Build 10)
 1.2 Software version: 1.2.0.10
 1.3 OpenCL C version: OpenCL C 2.0

1. Device: Intel(R) Gen9 HD Graphics NEO
 1.1 Hardware version: OpenCL 2.1 NEO
 1.2 Software version: 18.44.11760
 1.3 OpenCL C version: OpenCL C 2.0

its respective "icd" resides

./etc/OpenCL/vendors/intel_exp64.icd
./etc/OpenCL/vendors/intel.icd

Anconda3 where I have my "cl" environment created:
~/anaconda3/envs/cl/etc$ tree -L 2
.
└── OpenCL
    └── vendors

there is already dir structure ... but empty

what do I need to copy where?

**Comment by isuruf** [comment]
`cp /etc/OpenCL/vendors/*.icd ~/anaconda3/envs/cl/etc/OpenCL/vendors/`

**Comment by peter73421** [comment]
I got working :+1: 

I copied 

```
(cl) ~/anaconda3/envs/cl/etc$ tree
.
└── OpenCL
    └── vendors
        ├── intel_exp64.icd
        └── intel.icd
```
and now pyopencl in use


```
(cl) ~/anaconda3$ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> platforms = cl.get_platforms()
>>> print (*platforms, sep= "\n")
<pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x21031c0>
<pyopencl.Platform 'Experimental OpenCL 2.1 CPU Only Platform' at 0x219df40>
```

Thanks for help!
