### ISSUE TITLE
Build for Python 3.6 on Windows

### ISSUE THREAD

**Issue by snorfalorpagus** [conda-forge/pyopencl-feedstock#8]
There is a Python 3.6 build for OS X, but not Windows. Does this just need re-rendering?

**Comment by inducer** [comment]
Rerendered: #9.

But it's not looking like that would fix it...

**Comment by snorfalorpagus** [comment]
It looks like this package depends on `mingwpy`, which isn't available for Python 3.6 yet.

**Comment by inducer** [comment]
> It looks like this package depends on mingwpy, which isn't available for Python 3.6 yet.

mingwpy is only relevant for Py3.4 and lower.

**Comment by inducer** [comment]
#10 may fix this.

**Comment by inducer** [comment]
Actually, doesn't. Still only builds for 3.5. I removed the `mingwpy` dep on `py36`. Any ideas?

**Comment by inducer** [comment]
Thanks to @isuruf's help, #10 *will* fix this.

**Comment by inducer** [comment]
3.6 should be building now. Let me know if they haven't shown up by tomorrow at the latest. And thanks for the report.
