### ISSUE TITLE
appdirs vs platformdirs

### ISSUE THREAD

**Issue by goanpeca** [conda-forge/pyopencl-feedstock#82]
Hello @conda-forge/pyopencl, some packages that run `pip check` result in:

```
pytools 2022.1 requires platformdirs, which is not installed.
pyopencl 2022.1 requires platformdirs, which is not installed.
```

It seems pyopencl does prefer `platformdirs` (instead of `appdirs`) 
- https://github.com/inducer/pyopencl/commit/8e10b18f575f9bb8d0c39617764918f1d986dbfa
- https://github.com/inducer/pyopencl/blob/main/setup.py#L260

Should the recipe be updated to use `platformdirs` as run requirement?

Cheers!

**Comment by isuruf** [comment]
Sounds good. Can you send a PR?

**Comment by goanpeca** [comment]
Sure thing! :)
